// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CommunityToolkit.SampleIndex.Tests;

/// <summary>
/// The staleness gate: the committed index has to match what the samples produce right now.
/// </summary>
/// <remarks>
/// Without this, the index rots quietly. Someone edits a sample, the committed JSON keeps
/// describing the old one, and nothing anywhere says so — consumers keep serving markup that no
/// longer exists in the repository. Running this in CI turns that into a failed build with a
/// one-line fix.
/// </remarks>
[TestClass]
public class IndexUpToDateTests
{
    [TestMethod]
    public void CommittedIndexExists()
    {
        var path = Path.Combine(RepositoryIndex.Root, IndexGenerator.IndexRelativePath);

        Assert.IsTrue(
            File.Exists(path),
            $"{IndexGenerator.IndexRelativePath} is missing. Run "
            + "'dotnet run --project tools/SampleIndexExporter -- generate' and commit the result.");
    }

    [TestMethod]
    public void CommittedIndexMatchesTheSamples()
    {
        var path = Path.Combine(RepositoryIndex.Root, IndexGenerator.IndexRelativePath);
        var committed = File.ReadAllText(path).Replace("\r\n", "\n");
        var regenerated = IndexGenerator.Serialize(RepositoryIndex.Index);

        Assert.AreEqual(
            regenerated,
            committed,
            $"{IndexGenerator.IndexRelativePath} does not match the samples in this branch. Run "
            + "'dotnet run --project tools/SampleIndexExporter -- generate' and commit the result.");
    }

    [TestMethod]
    public void GeneratingTwiceProducesTheSameBytes()
    {
        // Catches in-process non-determinism only: a dictionary's iteration order, a hash set
        // reaching the output, a stray DateTime. It cannot see the filesystem-dependent kind,
        // which is what the test below is for.
        var first = IndexGenerator.Serialize(IndexGenerator.Generate(RepositoryIndex.Root).Index);
        var second = IndexGenerator.Serialize(IndexGenerator.Generate(RepositoryIndex.Root).Index);

        Assert.AreEqual(first, second, "Generating the index twice produced different output.");
    }

    [TestMethod]
    public void EntriesAreOrderedOrdinallyRatherThanByTheHostsIdeaOfOrder()
    {
        // The index is generated by contributors on Windows and byte-compared by a Linux CI
        // job, so every ordering has to mean the same thing on both. NTFS compares names
        // case-insensitively and ext4 does not; a culture-aware or case-insensitive comparer
        // would therefore agree with itself on one machine and disagree across the two,
        // producing a CI failure nobody could reproduce locally.
        //
        // These three names are chosen so ordinal order (uppercase first) and case-insensitive
        // order disagree: ordinal gives Beta, Gamma, alpha; case-insensitive gives alpha, Beta,
        // Gamma. Comparing two fixtures built in different orders would not catch this, because
        // NTFS hands directory entries back in name order whatever order they were created in.
        var root = Fixture.Create("Beta", "alpha", "Gamma");

        try
        {
            var entries = IndexGenerator.Generate(root).Index.Controls
                .Select(c => c.Toolkit!.DocumentPath)
                .ToList();

            CollectionAssert.AreEqual(
                new[]
                {
                    "components/Beta/samples/Beta.md",
                    "components/Gamma/samples/Gamma.md",
                    "components/alpha/samples/alpha.md",
                },
                entries,
                "Entries must be ordered ordinally, which is the only order both CI and a "
                    + "contributor's machine agree on.");
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    [TestMethod]
    public void EntriesAreOrderedByDocumentPath()
    {
        var paths = RepositoryIndex.Index.Controls.Select(c => c.Toolkit!.DocumentPath).ToList();
        var sorted = paths.OrderBy(p => p, StringComparer.Ordinal).ToList();

        CollectionAssert.AreEqual(
            sorted,
            paths,
            "Entries must be ordered by document path so that adding a sample produces a small diff.");
    }

    [TestMethod]
    public void SourceDataHasNoErrors()
    {
        var errors = RepositoryIndex.Result.Errors.Select(e => e.ToString()).ToList();

        Assert.AreEqual(
            0,
            errors.Count,
            "The sample sources have errors that stop the index being published:\n  "
            + string.Join("\n  ", errors));
    }
}
